export const searchBar = '#search_product'
export const searchIcon = '#submit_search'
export const btnaddToChart = '.productinfo > .btn'
export const modalContent= '#cartModal'
export const continueButton= '[id="cartModal"]'
export const viewCart= 'a:contains("View Cart")'
export const viewProduct= ':nth-child(3) > .product-image-wrapper > .choose > .nav > li > a'