export const emailField = '[data-qa="login-email"]'
export const passwordField = '[data-qa="login-password"]'
export const signinBtn = '[data-qa="login-button"]'
export const invalidEmailAlert = '.message-error'
export const signupNameField = '[data-qa="signup-name"]'
export const signupEmailField = '[data-qa="signup-email"]'
export const signupBtn = '[data-qa="signup-button"]'
export const btnchart = ':nth-child(5) > .btn'
export const btnProceed = '.col-sm-6 > .btn'
export const fromControl = '.form-control'
export const placeOrder = ':nth-child(7) > .btn'
export const nameOnCard = '[data-qa="name-on-card"]'
export const cardNumber = '[data-qa="card-number"]'
export const cvc = '[data-qa="cvc"]'
export const expirationMonth = '[data-qa="expiry-month"]'
export const expirationYear = '[data-qa="expiry-year"]'
export const payAndConfirm = '[data-qa="pay-button"]'
export const downloadInvoice = '.col-sm-9 > .btn-default'